name: Deploy
on:
  release:
    types:
      - published
jobs:
  release:
    name: Deploy
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Dependencies
        run: npm ci
      - name: Build
        run: |
          npm run build
          npm run apidoc
      - name: Assemble
        run: |
          mkdir -p pages/lib/jsdoc-type-pratt-parser/
          cp -r dist/* pages/lib/jsdoc-type-pratt-parser/
          cp -r docs pages/
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.3.1
        with:
          branch: gh-pages
          folder: pages
          clean-exclude: index.html
