name: Deploy
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Deploy
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Deploy gh-pages
        env:
          REPOSITORY: "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.REPOSITORY }}.git"
        run: ./deploy-pages.sh
